
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 31 22:47:35 EST 2002
//----------------------------------------------------

package silhouette.language;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int METHODSINPUT = 35;
  public static final int CHAR = 23;
  public static final int ASTERISK = 6;
  public static final int PFORMULA_NAME = 27;
  public static final int READONLY = 13;
  public static final int DOUBLE = 21;
  public static final int BEGIN_JAVA = 33;
  public static final int SEMI = 8;
  public static final int PRIVATE = 17;
  public static final int DOTTEDNAME = 43;
  public static final int INT = 18;
  public static final int REALNUMBER = 37;
  public static final int CHARACTER = 41;
  public static final int STATIC = 12;
  public static final int ARGUMENTINPUT = 29;
  public static final int COMMA = 7;
  public static final int CLASS = 11;
  public static final int DOT = 5;
  public static final int VALUEINPUT = 28;
  public static final int EOF = 0;
  public static final int BOOLEAN = 22;
  public static final int TRUE = 38;
  public static final int error = 1;
  public static final int FORMULAINPUT = 26;
  public static final int EQ = 4;
  public static final int INTEGERNUMBER = 36;
  public static final int IMPORT = 10;
  public static final int PART = 30;
  public static final int LCPAREN = 2;
  public static final int PROTECTED = 16;
  public static final int RCPAREN = 3;
  public static final int PACKAGE = 9;
  public static final int FINAL = 14;
  public static final int TEXTSTRING = 40;
  public static final int FLOAT = 20;
  public static final int END_JAVA = 34;
  public static final int PUBLIC = 15;
  public static final int FORMULA = 25;
  public static final int EXTENDS = 31;
  public static final int LONG = 19;
  public static final int STRING = 24;
  public static final int FALSE = 39;
  public static final int IMPLEMENTS = 32;
  public static final int IDENTIFIER = 42;
}

